import type { Recipe, Author } from "./types";

/* ------------------------------------------------------------------ */
/*  Mock Authors                                                       */
/* ------------------------------------------------------------------ */

const authors: Author[] = [
  { id: "1", name: "Maria Chen", avatar: undefined },
  { id: "2", name: "James Wilson", avatar: undefined },
  { id: "3", name: "Sofia Rodriguez", avatar: undefined },
  { id: "4", name: "Alex Kim", avatar: undefined },
  { id: "5", name: "Emma Taylor", avatar: undefined },
  { id: "current", name: "You", avatar: undefined },
];

/* ------------------------------------------------------------------ */
/*  Helper                                                             */
/* ------------------------------------------------------------------ */

let idCounter = 0;
function genId() {
  return `recipe-${++idCounter}`;
}

const today = new Date().toISOString();

/* ------------------------------------------------------------------ */
/*  Mock Recipes                                                       */
/* ------------------------------------------------------------------ */

export const mockRecipes: Recipe[] = [
  // Italian
  {
    id: genId(),
    title: "Creamy Tuscan Chicken",
    description:
      "Tender chicken breasts in a rich, creamy sun-dried tomato and spinach sauce. A restaurant-quality dish ready in 30 minutes.",
    image: undefined,
    placeholderType: "meat",
    author: authors[0],
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    difficulty: "medium",
    ingredients: [
      { name: "Chicken Breast", quantity: 4, unit: "pieces" },
      { name: "Spinach", quantity: 200, unit: "g" },
      { name: "Sun-dried Tomatoes", quantity: 100, unit: "g" },
      { name: "Heavy Cream", quantity: 200, unit: "ml" },
      { name: "Parmesan", quantity: 50, unit: "g" },
      { name: "Garlic", quantity: 4, unit: "cloves" },
      { name: "Olive Oil", quantity: 2, unit: "tbsp" },
      { name: "Italian Seasoning", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "Black Pepper", quantity: 0.5, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Season chicken breasts with salt, pepper, and Italian seasoning." },
      { step: 2, text: "Heat olive oil in a large skillet over medium-high heat. Cook chicken 6-7 minutes per side until golden and cooked through. Set aside." },
      { step: 3, text: "In the same pan, sauté minced garlic for 30 seconds until fragrant." },
      { step: 4, text: "Add sun-dried tomatoes and spinach, cook until spinach wilts." },
      { step: 5, text: "Pour in heavy cream and bring to a simmer. Stir in parmesan until melted." },
      { step: 6, text: "Return chicken to the pan, spoon sauce over top. Serve immediately." },
    ],
    nutrition: { calories: 485, protein: 42, carbs: 12, fat: 30 },
    mealType: ["dinner"],
    cuisine: "italian",
    dietaryTags: ["gluten-free"],
    rating: 4.8,
    reviewCount: 124,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Classic Spaghetti Carbonara",
    description:
      "Authentic Roman pasta with crispy guanciale, eggs, and pecorino. Simple ingredients, incredible flavor.",
    image: undefined,
    placeholderType: "pasta",
    author: authors[1],
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    difficulty: "medium",
    ingredients: [
      { name: "Spaghetti", quantity: 400, unit: "g" },
      { name: "Guanciale", quantity: 200, unit: "g" },
      { name: "Eggs", quantity: 4, unit: "pieces" },
      { name: "Pecorino Romano", quantity: 100, unit: "g" },
      { name: "Black Pepper", quantity: 2, unit: "tsp" },
      { name: "Salt", quantity: 1, unit: "tbsp" },
    ],
    instructions: [
      { step: 1, text: "Bring a large pot of salted water to boil. Cook spaghetti until al dente." },
      { step: 2, text: "Cut guanciale into small strips. Cook in a cold pan over medium heat until crispy." },
      { step: 3, text: "Whisk eggs with grated pecorino and plenty of black pepper." },
      { step: 4, text: "Reserve 1 cup pasta water, then drain spaghetti." },
      { step: 5, text: "Remove pan from heat, add hot pasta to guanciale. Toss quickly." },
      { step: 6, text: "Add egg mixture, tossing constantly. Add pasta water as needed for creamy sauce." },
    ],
    nutrition: { calories: 650, protein: 28, carbs: 72, fat: 28 },
    mealType: ["dinner", "lunch"],
    cuisine: "italian",
    dietaryTags: [],
    rating: 4.9,
    reviewCount: 289,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // Mexican
  {
    id: genId(),
    title: "Street-Style Chicken Tacos",
    description:
      "Juicy lime-marinated chicken with fresh pico de gallo, creamy avocado, and tangy crema on warm corn tortillas.",
    image: undefined,
    placeholderType: "mexican",
    author: authors[2],
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    difficulty: "easy",
    ingredients: [
      { name: "Chicken Thighs", quantity: 500, unit: "g" },
      { name: "Corn Tortillas", quantity: 12, unit: "pieces" },
      { name: "Lime", quantity: 3, unit: "pieces" },
      { name: "Avocado", quantity: 2, unit: "pieces" },
      { name: "Tomatoes", quantity: 2, unit: "pieces" },
      { name: "Onions", quantity: 1, unit: "pieces" },
      { name: "Cilantro", quantity: 1, unit: "bunch" },
      { name: "Sour Cream", quantity: 100, unit: "ml" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Chili Powder", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Marinate chicken in lime juice, cumin, chili powder, salt for 15 minutes." },
      { step: 2, text: "Make pico de gallo: dice tomatoes, onion, cilantro. Mix with lime juice and salt." },
      { step: 3, text: "Grill or pan-fry chicken until charred and cooked through, about 6 minutes per side." },
      { step: 4, text: "Let chicken rest 5 minutes, then slice into strips." },
      { step: 5, text: "Warm tortillas in a dry pan or directly over flame." },
      { step: 6, text: "Assemble tacos with chicken, pico, sliced avocado, and drizzle of crema." },
    ],
    nutrition: { calories: 380, protein: 32, carbs: 28, fat: 18 },
    mealType: ["dinner", "lunch"],
    cuisine: "mexican",
    dietaryTags: ["gluten-free"],
    rating: 4.7,
    reviewCount: 98,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Loaded Veggie Burrito Bowl",
    description:
      "A colorful, filling bowl with cilantro-lime rice, black beans, roasted corn, and all your favorite toppings.",
    image: undefined,
    placeholderType: "mexican",
    author: authors[3],
    servings: 2,
    prepTime: 15,
    cookTime: 25,
    difficulty: "easy",
    ingredients: [
      { name: "Basmati Rice", quantity: 200, unit: "g" },
      { name: "Black Beans", quantity: 400, unit: "g" },
      { name: "Corn", quantity: 200, unit: "g" },
      { name: "Bell Peppers", quantity: 2, unit: "pieces" },
      { name: "Avocado", quantity: 1, unit: "pieces" },
      { name: "Lime", quantity: 2, unit: "pieces" },
      { name: "Cilantro", quantity: 1, unit: "bunch" },
      { name: "Greek Yogurt", quantity: 100, unit: "g" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Cook rice according to package. Fluff with lime juice and chopped cilantro." },
      { step: 2, text: "Roast corn in a hot pan until charred. Season with salt and lime." },
      { step: 3, text: "Warm black beans with cumin and a splash of water." },
      { step: 4, text: "Slice bell peppers into strips, sauté until slightly softened." },
      { step: 5, text: "Assemble bowls: rice base, topped with beans, corn, peppers, sliced avocado." },
      { step: 6, text: "Drizzle with lime crema (yogurt + lime juice + salt)." },
    ],
    nutrition: { calories: 520, protein: 18, carbs: 78, fat: 16 },
    mealType: ["lunch", "dinner"],
    cuisine: "mexican",
    dietaryTags: ["vegetarian", "gluten-free"],
    rating: 4.5,
    reviewCount: 67,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // Asian
  {
    id: genId(),
    title: "Teriyaki Salmon with Broccoli",
    description:
      "Glazed salmon fillets with homemade teriyaki sauce, served over steamed rice with crispy broccoli.",
    image: undefined,
    placeholderType: "asian",
    author: authors[4],
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    difficulty: "easy",
    ingredients: [
      { name: "Salmon Fillet", quantity: 2, unit: "pieces" },
      { name: "Broccoli", quantity: 300, unit: "g" },
      { name: "Jasmine Rice", quantity: 200, unit: "g" },
      { name: "Soy Sauce", quantity: 60, unit: "ml" },
      { name: "Honey", quantity: 3, unit: "tbsp" },
      { name: "Garlic", quantity: 2, unit: "cloves" },
      { name: "Ginger", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tbsp" },
      { name: "Sesame Seeds", quantity: 1, unit: "tbsp" },
    ],
    instructions: [
      { step: 1, text: "Cook rice according to package instructions." },
      { step: 2, text: "Make teriyaki sauce: whisk soy sauce, honey, minced garlic, and grated ginger." },
      { step: 3, text: "Heat sesame oil in a pan. Sear salmon skin-side up for 3 minutes." },
      { step: 4, text: "Flip salmon, pour teriyaki sauce over. Cook 4-5 minutes, basting often." },
      { step: 5, text: "Steam or roast broccoli until bright green and slightly crispy." },
      { step: 6, text: "Serve salmon over rice with broccoli. Garnish with sesame seeds and extra sauce." },
    ],
    nutrition: { calories: 580, protein: 45, carbs: 52, fat: 22 },
    mealType: ["dinner"],
    cuisine: "asian",
    dietaryTags: ["dairy-free"],
    rating: 4.8,
    reviewCount: 156,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Vegetable Pad Thai",
    description:
      "Classic Thai stir-fried noodles with tofu, crunchy vegetables, and a sweet-tangy tamarind sauce.",
    image: undefined,
    placeholderType: "asian",
    author: authors[0],
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    difficulty: "medium",
    ingredients: [
      { name: "Rice Noodles", quantity: 250, unit: "g" },
      { name: "Tofu", quantity: 200, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Bean Sprouts", quantity: 150, unit: "g" },
      { name: "Carrots", quantity: 2, unit: "pieces" },
      { name: "Green Onions", quantity: 4, unit: "pieces" },
      { name: "Peanuts", quantity: 50, unit: "g" },
      { name: "Tamarind Paste", quantity: 2, unit: "tbsp" },
      { name: "Fish Sauce", quantity: 3, unit: "tbsp" },
      { name: "Brown Sugar", quantity: 2, unit: "tbsp" },
      { name: "Lime", quantity: 1, unit: "pieces" },
    ],
    instructions: [
      { step: 1, text: "Soak rice noodles in warm water for 30 minutes until pliable. Drain." },
      { step: 2, text: "Press and cube tofu. Fry until golden on all sides. Set aside." },
      { step: 3, text: "Make sauce: mix tamarind paste, fish sauce, and brown sugar." },
      { step: 4, text: "Scramble eggs in wok, set aside. Stir-fry julienned carrots until slightly soft." },
      { step: 5, text: "Add noodles and sauce to wok. Toss until noodles absorb sauce." },
      { step: 6, text: "Add tofu, eggs, bean sprouts, green onions. Serve with crushed peanuts and lime." },
    ],
    nutrition: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    mealType: ["dinner", "lunch"],
    cuisine: "asian",
    dietaryTags: ["vegetarian", "dairy-free"],
    rating: 4.6,
    reviewCount: 203,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  // Mediterranean
  {
    id: genId(),
    title: "Greek Chicken Souvlaki",
    description:
      "Herb-marinated grilled chicken skewers with tzatziki, fresh vegetables, and warm pita bread.",
    image: undefined,
    placeholderType: "meat",
    author: authors[1],
    servings: 4,
    prepTime: 25,
    cookTime: 15,
    difficulty: "easy",
    ingredients: [
      { name: "Chicken Breast", quantity: 600, unit: "g" },
      { name: "Greek Yogurt", quantity: 200, unit: "g" },
      { name: "Cucumber", quantity: 1, unit: "pieces" },
      { name: "Pita Bread", quantity: 4, unit: "pieces" },
      { name: "Tomatoes", quantity: 2, unit: "pieces" },
      { name: "Red Onion", quantity: 1, unit: "pieces" },
      { name: "Lemon", quantity: 2, unit: "pieces" },
      { name: "Garlic", quantity: 4, unit: "cloves" },
      { name: "Olive Oil", quantity: 4, unit: "tbsp" },
      { name: "Oregano", quantity: 2, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Cube chicken. Marinate in olive oil, lemon juice, garlic, oregano for 20 minutes." },
      { step: 2, text: "Make tzatziki: grate cucumber, squeeze dry. Mix with yogurt, garlic, lemon, dill." },
      { step: 3, text: "Thread chicken onto skewers. Grill over high heat 3-4 minutes per side." },
      { step: 4, text: "Dice tomatoes and red onion for a quick salad. Dress with olive oil and lemon." },
      { step: 5, text: "Warm pita bread on the grill for 30 seconds per side." },
      { step: 6, text: "Serve skewers with tzatziki, salad, and warm pita." },
    ],
    nutrition: { calories: 410, protein: 38, carbs: 32, fat: 16 },
    mealType: ["dinner", "lunch"],
    cuisine: "mediterranean",
    dietaryTags: [],
    rating: 4.7,
    reviewCount: 89,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Mediterranean Quinoa Salad",
    description:
      "Protein-packed quinoa with cherry tomatoes, cucumber, feta, olives, and a lemon-herb dressing.",
    image: undefined,
    placeholderType: "salad",
    author: authors[2],
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    difficulty: "easy",
    ingredients: [
      { name: "Quinoa", quantity: 200, unit: "g" },
      { name: "Cherry Tomatoes", quantity: 250, unit: "g" },
      { name: "Cucumber", quantity: 1, unit: "pieces" },
      { name: "Feta Cheese", quantity: 100, unit: "g" },
      { name: "Kalamata Olives", quantity: 80, unit: "g" },
      { name: "Red Onion", quantity: 0.5, unit: "pieces" },
      { name: "Parsley", quantity: 1, unit: "bunch" },
      { name: "Olive Oil", quantity: 4, unit: "tbsp" },
      { name: "Lemon", quantity: 1, unit: "pieces" },
    ],
    instructions: [
      { step: 1, text: "Rinse quinoa, cook in salted water until fluffy. Cool to room temperature." },
      { step: 2, text: "Halve cherry tomatoes, dice cucumber, slice red onion thinly." },
      { step: 3, text: "Chop parsley, pit and halve olives, crumble feta." },
      { step: 4, text: "Make dressing: whisk olive oil, lemon juice, salt, pepper, dried oregano." },
      { step: 5, text: "Combine quinoa with all vegetables in a large bowl." },
      { step: 6, text: "Toss with dressing, top with feta and extra herbs. Serve cold or at room temp." },
    ],
    nutrition: { calories: 340, protein: 12, carbs: 38, fat: 18 },
    mealType: ["lunch"],
    cuisine: "mediterranean",
    dietaryTags: ["vegetarian", "gluten-free"],
    rating: 4.5,
    reviewCount: 112,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // American
  {
    id: genId(),
    title: "Classic Smash Burger",
    description:
      "Crispy-edged beef patties with melted American cheese, special sauce, pickles, and onions on a soft bun.",
    image: undefined,
    placeholderType: "meat",
    author: authors[3],
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    difficulty: "easy",
    ingredients: [
      { name: "Ground Beef", quantity: 300, unit: "g" },
      { name: "Burger Buns", quantity: 2, unit: "pieces" },
      { name: "American Cheese", quantity: 4, unit: "slices" },
      { name: "Pickles", quantity: 8, unit: "slices" },
      { name: "Onions", quantity: 0.5, unit: "pieces" },
      { name: "Lettuce", quantity: 4, unit: "leaves" },
      { name: "Mayonnaise", quantity: 2, unit: "tbsp" },
      { name: "Ketchup", quantity: 1, unit: "tbsp" },
      { name: "Mustard", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Divide beef into 4 balls (about 75g each). Season with salt and pepper." },
      { step: 2, text: "Heat cast iron skillet until smoking hot." },
      { step: 3, text: "Place balls on skillet, smash flat with spatula. Cook 2 minutes until crispy." },
      { step: 4, text: "Flip, add cheese immediately. Cook 1 more minute." },
      { step: 5, text: "Mix mayo, ketchup, mustard for special sauce. Toast buns." },
      { step: 6, text: "Stack: bottom bun, sauce, lettuce, 2 patties, pickles, onion, top bun." },
    ],
    nutrition: { calories: 620, protein: 35, carbs: 38, fat: 38 },
    mealType: ["dinner", "lunch"],
    cuisine: "american",
    dietaryTags: [],
    rating: 4.9,
    reviewCount: 234,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Buffalo Cauliflower Wings",
    description:
      "Crispy baked cauliflower florets tossed in spicy buffalo sauce with cooling ranch dip.",
    image: undefined,
    placeholderType: "meat",
    author: authors[4],
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    difficulty: "easy",
    ingredients: [
      { name: "Cauliflower", quantity: 1, unit: "head" },
      { name: "Flour", quantity: 100, unit: "g" },
      { name: "Hot Sauce", quantity: 120, unit: "ml" },
      { name: "Butter", quantity: 60, unit: "g" },
      { name: "Garlic Powder", quantity: 1, unit: "tsp" },
      { name: "Milk", quantity: 120, unit: "ml" },
      { name: "Ranch Dressing", quantity: 100, unit: "ml" },
      { name: "Celery", quantity: 4, unit: "stalks" },
    ],
    instructions: [
      { step: 1, text: "Preheat oven to 220°C (425°F). Line baking sheet with parchment." },
      { step: 2, text: "Cut cauliflower into bite-sized florets." },
      { step: 3, text: "Make batter: whisk flour, milk, garlic powder, salt. Dip florets to coat." },
      { step: 4, text: "Bake florets 20 minutes until golden and crispy." },
      { step: 5, text: "Melt butter with hot sauce to make buffalo sauce." },
      { step: 6, text: "Toss baked cauliflower in buffalo sauce. Serve with ranch and celery sticks." },
    ],
    nutrition: { calories: 280, protein: 8, carbs: 28, fat: 16 },
    mealType: ["snack", "dinner"],
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    rating: 4.4,
    reviewCount: 78,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // Indian
  {
    id: genId(),
    title: "Butter Chicken",
    description:
      "Tender chicken in a rich, creamy tomato sauce with warm spices. A beloved classic.",
    image: undefined,
    placeholderType: "meat",
    author: authors[0],
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    difficulty: "medium",
    ingredients: [
      { name: "Chicken Thighs", quantity: 600, unit: "g" },
      { name: "Greek Yogurt", quantity: 150, unit: "g" },
      { name: "Tomato Paste", quantity: 3, unit: "tbsp" },
      { name: "Heavy Cream", quantity: 200, unit: "ml" },
      { name: "Butter", quantity: 60, unit: "g" },
      { name: "Onions", quantity: 1, unit: "pieces" },
      { name: "Garlic", quantity: 4, unit: "cloves" },
      { name: "Ginger", quantity: 2, unit: "tbsp" },
      { name: "Garam Masala", quantity: 2, unit: "tsp" },
      { name: "Turmeric", quantity: 1, unit: "tsp" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Basmati Rice", quantity: 300, unit: "g" },
    ],
    instructions: [
      { step: 1, text: "Marinate chicken in yogurt, turmeric, cumin, salt for 15 minutes." },
      { step: 2, text: "Grill or pan-fry chicken until charred. Cut into pieces." },
      { step: 3, text: "Sauté onion in butter until soft. Add garlic and ginger, cook 1 minute." },
      { step: 4, text: "Add tomato paste and garam masala. Cook until darkened, 2 minutes." },
      { step: 5, text: "Add cream and simmer 10 minutes. Add chicken, cook 5 more minutes." },
      { step: 6, text: "Serve over basmati rice with fresh cilantro and naan." },
    ],
    nutrition: { calories: 520, protein: 38, carbs: 24, fat: 32 },
    mealType: ["dinner"],
    cuisine: "indian",
    dietaryTags: ["gluten-free"],
    rating: 4.9,
    reviewCount: 312,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Chana Masala",
    description:
      "Hearty chickpea curry in a fragrant tomato-onion gravy. Vegan comfort food at its best.",
    image: undefined,
    placeholderType: "soup",
    author: authors[1],
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    difficulty: "easy",
    ingredients: [
      { name: "Chickpeas", quantity: 800, unit: "g" },
      { name: "Diced Tomatoes", quantity: 400, unit: "g" },
      { name: "Onions", quantity: 2, unit: "pieces" },
      { name: "Garlic", quantity: 4, unit: "cloves" },
      { name: "Ginger", quantity: 1, unit: "tbsp" },
      { name: "Cumin", quantity: 1, unit: "tsp" },
      { name: "Coriander", quantity: 1, unit: "tsp" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Garam Masala", quantity: 1, unit: "tsp" },
      { name: "Cilantro", quantity: 1, unit: "bunch" },
    ],
    instructions: [
      { step: 1, text: "Sauté diced onions in oil until golden, about 8 minutes." },
      { step: 2, text: "Add garlic and ginger, cook 1 minute until fragrant." },
      { step: 3, text: "Add cumin, coriander, turmeric. Toast spices 30 seconds." },
      { step: 4, text: "Add tomatoes and simmer 5 minutes until thickened." },
      { step: 5, text: "Add drained chickpeas and 1/2 cup water. Simmer 15 minutes." },
      { step: 6, text: "Stir in garam masala and fresh cilantro. Serve with rice or naan." },
    ],
    nutrition: { calories: 320, protein: 14, carbs: 52, fat: 8 },
    mealType: ["dinner", "lunch"],
    cuisine: "indian",
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    rating: 4.6,
    reviewCount: 145,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // French
  {
    id: genId(),
    title: "French Onion Soup",
    description:
      "Caramelized onions in rich beef broth, topped with crusty bread and melted Gruyère cheese.",
    image: undefined,
    placeholderType: "soup",
    author: authors[2],
    servings: 4,
    prepTime: 15,
    cookTime: 60,
    difficulty: "medium",
    ingredients: [
      { name: "Onions", quantity: 1000, unit: "g" },
      { name: "Beef Broth", quantity: 1000, unit: "ml" },
      { name: "Butter", quantity: 60, unit: "g" },
      { name: "Gruyère Cheese", quantity: 200, unit: "g" },
      { name: "Sourdough Bread", quantity: 4, unit: "slices" },
      { name: "Dry White Wine", quantity: 120, unit: "ml" },
      { name: "Thyme", quantity: 4, unit: "sprigs" },
      { name: "Bay Leaves", quantity: 2, unit: "pieces" },
    ],
    instructions: [
      { step: 1, text: "Slice onions thinly. Melt butter in large pot over medium-low heat." },
      { step: 2, text: "Add onions, cook 45 minutes, stirring occasionally until deeply caramelized." },
      { step: 3, text: "Add wine, scraping up browned bits. Cook until evaporated." },
      { step: 4, text: "Add broth, thyme, bay leaves. Simmer 15 minutes. Season to taste." },
      { step: 5, text: "Ladle soup into oven-safe bowls. Top with bread slice and grated Gruyère." },
      { step: 6, text: "Broil until cheese is bubbly and golden, 2-3 minutes. Serve immediately." },
    ],
    nutrition: { calories: 380, protein: 18, carbs: 32, fat: 22 },
    mealType: ["dinner", "lunch"],
    cuisine: "french",
    dietaryTags: [],
    rating: 4.7,
    reviewCount: 167,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // Breakfast
  {
    id: genId(),
    title: "Fluffy Blueberry Pancakes",
    description:
      "Light, fluffy pancakes bursting with fresh blueberries, served with maple syrup and butter.",
    image: undefined,
    placeholderType: "breakfast",
    author: authors[3],
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    difficulty: "easy",
    ingredients: [
      { name: "Flour", quantity: 200, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Milk", quantity: 250, unit: "ml" },
      { name: "Blueberries", quantity: 150, unit: "g" },
      { name: "Butter", quantity: 30, unit: "g" },
      { name: "Baking Powder", quantity: 2, unit: "tsp" },
      { name: "Sugar", quantity: 2, unit: "tbsp" },
      { name: "Maple Syrup", quantity: 100, unit: "ml" },
      { name: "Vanilla Extract", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Whisk flour, baking powder, sugar, and pinch of salt in a large bowl." },
      { step: 2, text: "In another bowl, whisk eggs, milk, melted butter, and vanilla." },
      { step: 3, text: "Pour wet ingredients into dry. Stir until just combined (lumps are OK)." },
      { step: 4, text: "Gently fold in blueberries." },
      { step: 5, text: "Heat buttered pan over medium. Pour 1/4 cup batter per pancake. Cook until bubbles form, flip, cook 1-2 minutes more." },
      { step: 6, text: "Stack pancakes, top with butter and warm maple syrup." },
    ],
    nutrition: { calories: 380, protein: 10, carbs: 58, fat: 12 },
    mealType: ["breakfast"],
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    rating: 4.8,
    reviewCount: 198,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: genId(),
    title: "Avocado Toast with Poached Eggs",
    description:
      "Creamy smashed avocado on sourdough with perfectly poached eggs and a sprinkle of everything seasoning.",
    image: undefined,
    placeholderType: "breakfast",
    author: authors[4],
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    difficulty: "medium",
    ingredients: [
      { name: "Sourdough Bread", quantity: 2, unit: "slices" },
      { name: "Avocado", quantity: 1, unit: "pieces" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Lemon", quantity: 0.5, unit: "pieces" },
      { name: "Chili Flakes", quantity: 0.5, unit: "tsp" },
      { name: "Everything Bagel Seasoning", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Bring a pot of water to gentle simmer. Add splash of vinegar." },
      { step: 2, text: "Toast sourdough slices until golden and crispy." },
      { step: 3, text: "Mash avocado with lemon juice, salt, and chili flakes." },
      { step: 4, text: "Create a gentle whirlpool in water, slide in eggs one at a time. Poach 3 minutes." },
      { step: 5, text: "Spread avocado generously on toast." },
      { step: 6, text: "Top with poached eggs, sprinkle everything seasoning. Season with salt and pepper." },
    ],
    nutrition: { calories: 320, protein: 14, carbs: 28, fat: 18 },
    mealType: ["breakfast"],
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    rating: 4.6,
    reviewCount: 134,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  // Dessert
  {
    id: genId(),
    title: "Chocolate Lava Cakes",
    description:
      "Individual chocolate cakes with a molten center that flows when you cut into them. Decadent and impressive.",
    image: undefined,
    placeholderType: "dessert",
    author: authors[0],
    servings: 4,
    prepTime: 15,
    cookTime: 12,
    difficulty: "medium",
    ingredients: [
      { name: "Dark Chocolate", quantity: 200, unit: "g" },
      { name: "Butter", quantity: 100, unit: "g" },
      { name: "Eggs", quantity: 4, unit: "pieces" },
      { name: "Sugar", quantity: 100, unit: "g" },
      { name: "Flour", quantity: 50, unit: "g" },
      { name: "Vanilla Extract", quantity: 1, unit: "tsp" },
      { name: "Powdered Sugar", quantity: 2, unit: "tbsp" },
    ],
    instructions: [
      { step: 1, text: "Preheat oven to 220°C (425°F). Butter and flour 4 ramekins." },
      { step: 2, text: "Melt chocolate and butter together. Let cool slightly." },
      { step: 3, text: "Whisk eggs, sugar, and vanilla until thick and pale." },
      { step: 4, text: "Fold chocolate mixture into eggs. Gently fold in flour." },
      { step: 5, text: "Divide batter among ramekins. Bake 10-12 minutes until edges are set but center jiggles." },
      { step: 6, text: "Let rest 1 minute, invert onto plates. Dust with powdered sugar. Serve immediately." },
    ],
    nutrition: { calories: 480, protein: 8, carbs: 42, fat: 32 },
    mealType: ["dessert"],
    cuisine: "french",
    dietaryTags: ["vegetarian"],
    rating: 4.9,
    reviewCount: 256,
    isPublished: true,
    isFavorite: true,
    createdAt: today,
    updatedAt: today,
  },
  // Snack
  {
    id: genId(),
    title: "Homemade Hummus",
    description:
      "Silky smooth chickpea dip with tahini, lemon, and garlic. Perfect with warm pita or fresh vegetables.",
    image: undefined,
    placeholderType: "salad",
    author: authors[1],
    servings: 6,
    prepTime: 10,
    cookTime: 0,
    difficulty: "easy",
    ingredients: [
      { name: "Chickpeas", quantity: 400, unit: "g" },
      { name: "Tahini", quantity: 60, unit: "g" },
      { name: "Lemon", quantity: 1, unit: "pieces" },
      { name: "Garlic", quantity: 2, unit: "cloves" },
      { name: "Olive Oil", quantity: 3, unit: "tbsp" },
      { name: "Cumin", quantity: 0.5, unit: "tsp" },
      { name: "Paprika", quantity: 0.5, unit: "tsp" },
    ],
    instructions: [
      { step: 1, text: "Drain chickpeas, reserving liquid (aquafaba). Rinse well." },
      { step: 2, text: "Add chickpeas, tahini, lemon juice, garlic, cumin to food processor." },
      { step: 3, text: "Blend, streaming in olive oil and aquafaba until silky smooth." },
      { step: 4, text: "Season with salt to taste. Blend again." },
      { step: 5, text: "Transfer to serving bowl, create swirls with spoon." },
      { step: 6, text: "Drizzle with olive oil, sprinkle paprika and cumin. Serve with pita." },
    ],
    nutrition: { calories: 180, protein: 6, carbs: 18, fat: 10 },
    mealType: ["snack"],
    cuisine: "mediterranean",
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    rating: 4.5,
    reviewCount: 89,
    isPublished: true,
    isFavorite: false,
    createdAt: today,
    updatedAt: today,
  },
  // User's draft recipe
  {
    id: genId(),
    title: "My Grandma's Pasta Sauce",
    description:
      "A family recipe passed down through generations. Rich, hearty, and full of love.",
    image: undefined,
    placeholderType: "pasta",
    author: authors[5], // "You"
    servings: 6,
    prepTime: 15,
    cookTime: 120,
    difficulty: "easy",
    ingredients: [
      { name: "Diced Tomatoes", quantity: 800, unit: "g" },
      { name: "Ground Beef", quantity: 500, unit: "g" },
      { name: "Onions", quantity: 2, unit: "pieces" },
      { name: "Garlic", quantity: 6, unit: "cloves" },
      { name: "Basil", quantity: 1, unit: "bunch" },
      { name: "Oregano", quantity: 2, unit: "tsp" },
      { name: "Red Wine", quantity: 120, unit: "ml" },
      { name: "Olive Oil", quantity: 3, unit: "tbsp" },
    ],
    instructions: [
      { step: 1, text: "Brown ground beef in olive oil. Drain excess fat." },
      { step: 2, text: "Add diced onions, cook until translucent." },
      { step: 3, text: "Add garlic, cook 1 minute." },
      { step: 4, text: "Pour in red wine, let it reduce by half." },
      { step: 5, text: "Add tomatoes, oregano, and half the basil. Simmer low for 2 hours." },
      { step: 6, text: "Finish with fresh basil. Season to taste." },
    ],
    nutrition: { calories: 340, protein: 22, carbs: 18, fat: 20 },
    mealType: ["dinner"],
    cuisine: "italian",
    dietaryTags: ["dairy-free"],
    rating: 0,
    reviewCount: 0,
    isPublished: false, // Draft
    isOwned: true,
    createdAt: today,
    updatedAt: today,
  },
];

/* ------------------------------------------------------------------ */
/*  Helper functions                                                   */
/* ------------------------------------------------------------------ */

export function getRecipeById(id: string): Recipe | undefined {
  return mockRecipes.find((r) => r.id === id);
}

export function getFavoriteRecipes(): Recipe[] {
  return mockRecipes.filter((r) => r.isFavorite);
}

export function getMyRecipes(): Recipe[] {
  return mockRecipes.filter((r) => r.isOwned);
}

export function getPublishedRecipes(): Recipe[] {
  return mockRecipes.filter((r) => r.isPublished);
}
